HouseRentingSystem/HouseRentingSystem/Controllers/ContractController.cs
using HouseRentingSystem.Models;
using HouseRentingSystem.Repository;
using HouseRentingSystem.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HouseRentingSystem.Controllers
{
    [Authorize]
    public class ContractController : Controller
    {
        private readonly IContractRepository _contractRepository = null;
        private readonly ICreditCardRepository _creditCardRepository = null;
        private readonly IUserService _userService = null;

        public ContractController(IContractRepository contractRepository, 
            ICreditCardRepository creditCardRepository,
            IUserService userService)
        {
            _contractRepository = contractRepository;
            _creditCardRepository = creditCardRepository;
            _userService = userService;
        }

        public IActionResult Index()
        {
            List<ContractsModel> contracts = _contractRepository.GetContractsByUserId(_userService.GetUserId()).Result;
            return View(contracts);
        }

        public async Task<IActionResult> Select(int adid)
        {
            var userid = _userService.GetUserId();
            ViewBag.Adid = adid;
            ViewBag.returnUrl = "/Contract/Select";
            var model = await _creditCardRepository.GetCreditCardByUserid(userid);
            foreach(var m in model)
            {
                m.adid = adid;
            }
            return View(model);
        }

        public async Task<IActionResult> Rent(int cid, int adid)
        {
            var tenantid = _userService.GetUserId();
            await _contractRepository.AddContract(adid,cid,tenantid);
            return RedirectToAction(nameof(Index));
        }

        // GET: CreditCard/Create
        public IActionResult Create(int adid)
        {
            ViewBag.adid = adid;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cid,Userid,Cardnumber,Cardtype,Expireyear,Expiremonth,CardHolderName,adid")] CreditCardModel creditCardModel)
        {
            if (ModelState.IsValid)
            {
                creditCardModel.Userid = _userService.GetUserId();
                await _creditCardRepository.AddNewCreditCard(creditCardModel);
                ViewBag.adid = creditCardModel.adid;
                return RedirectToAction(nameof(Select),new {adid= creditCardModel.adid });
            }
            return View(creditCardModel);
        }
    }
}

HouseRentingSystem/HouseRentingSystem/Controllers/StarController.cs
using HouseRentingSystem.Repository;
using HouseRentingSystem.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HouseRentingSystem.Controllers
{
    [Authorize]
    public class StarController : Controller
    {
        private readonly IStarRepository _starRepository=null;
        private readonly IAdvertisementRepository _advertisementRepository = null;
        private readonly IUserService _userService = null;

        public StarController(IStarRepository starRepository, IUserService userService, IAdvertisementRepository advertisementRepository)
        {
            _starRepository = starRepository;
            _userService = userService;
            _advertisementRepository = advertisementRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddStar(int adId)
        {
            await _starRepository.AddStar(_userService.GetUserId(),adId);
            return RedirectToAction("GetAdvertisement", "Advertisement", new { AdId = adId });
        }
        public async Task<IActionResult> RemoveStar(int adId)
        {
            await _starRepository.RemoveStar(_userService.GetUserId(),adId);
            return RedirectToAction("GetAdvertisement", "Advertisement", new { AdId = adId });
        }
        public async Task<ViewResult> GetStarListAdvertisements()
        {
            var data = await _advertisementRepository.GetStarListAdvertisementsByUserId(_userService.GetUserId());
            return View(data);
        }
    }
}

HouseRentingSystem/HouseRentingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HouseRentingSystem</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/Site.css" rel="stylesheet" />
        <link href="~/css/NewStyle.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        @*<link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@

        <link rel="stylesheet"
              href="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity=""
              crossorigin="anonymous">

        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HouseRentingSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_SigninInfo" />            
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advertisement" asp-action="managead">Manage Ad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advertisement" asp-action="GetAllAdvertisements">All Ad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Star" asp-action="GetStarListAdvertisements">Favourite</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditCard" asp-action="index">CreditCards</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contract" asp-action="index">Contracts</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    @*    <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@
    <main role="main">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HouseRentingSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/jquery-validate/jquery.validate.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    </environment>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    @*    <script src="~/lib/react/umd/react.development.js"></script>
        <script src="~/lib/react-dom/umd/react-dom.development.js"></script>*@
    <script src="~/lib/react/umd/react.production.min.js"></script>
    <script src="~/lib/react-dom/umd/react-dom.production.min.js"></script>
    <script src="~/babel/standalone/babel.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HouseRentingSystem/HouseRentingSystem/Views/Shared/_SigninInfo.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager

@if (_signInManager.IsSignedIn(User))
{
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Hello @(User.FindFirst("UserFirstName").Value+" "+ User.FindFirst("UserLastName").Value)
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" asp-action="Logout" asp-controller="Account">Logout</a>
    </div>
    <a class="btn btn-outline-primary" href="/Advertisement/postad">Post ad</a>
</li>
}
else
{
    <li class="navbar-nav">
        <a class="nav-link text-dark" asp-controller="Account" asp-action="Signin" asp-route-returnUrl="@Context.Request.Path">Signin</a>
        <a class="nav-link text-dark">or</a>
        <a class="nav-link text-dark" asp-controller="Account" asp-action="Signup">Signup</a>
    </li>
}